export const ANSWERS_PT_BR: string[] = [
  'Um saco de feijão mágico.',
  'Um café da manhã balanceado.',
  'Um pênis gigante.',
  'Um moinho cheio de cadáveres.',
  'Pegar fogo.',
  'Justiça com as próprias mãos.',
  'Um mímico tendo um derrame.',
  'Gravidez na adolescência.',
  'Um microporco de capinha de chuva.',
  'Ciência.',
  'Rezar para a cura gay.',
  'Robôs voadores que matam pessoas.',
  'Sopa quente demais.',
  'Uma festa de aniversário decepcionante.',
  'A inevitável morte térmica do universo.',
  'Um chapéu muito maneiro.',
  'Derrubar um lustre nos seus inimigos.',
  'Os profundamente debilitados.',
  'Agricultura.',
  'Um falcão de boné na cabeça.',
  'O vazio.',
  'Gloryholes.',
  'Destruição mútua assegurada.',
  'Um policial honesto sem nada a perder.',
  'Combustão humana espontânea.',
  'Fermento.',
  'O Papa.',
  'Um pombo com síndrome do impostor.',
  'O grupo do zap da família.',
  'Um churrasco de gato.',
  'Cair na malha fina do leão.',
  'Um funk de 2012.',
  'O dedo podre para relacionamentos.',
  'Um estagiário sem salário.',
  'A conta de luz no fim do mês.',
  'Um influencer cancelado.',
  'O cabelo do Neymar.',
  'Um motoboy em alta velocidade.',
  'A fila do SUS.',
  'Um coach quântico.',
  'O chefe no grupo do trabalho.',
  'Um boleto vencido.',
  'A sogra no almoço de domingo.',
  'Um axé dos anos 90.',
  'O sinal do celular no elevador.',
  'Um príncipe encantado desempregado.',
  'A resposta automática de e-mail.',
  'Um pneu furado na estrada.',
  'O golpe do pix.',
  'Um churrasco sem cerveja.',
  'A prova de matemática amanhã.',
  'Um bicho-preguiça no trânsito.',
  'O botão de soneca.',
  'Um desodorante vencido.',
  'A tia que pergunta quando você vai casar.',
  'Um banho gelado de madrugada.',
  'O ronco do vizinho.',
  'Uma feijoada estragada.',
  'O algoritmo das redes sociais.',
  'Um casamento que começou no Tinder.',
  'A última fatia de pizza.',
  'Um dente de alho no arroz.',
  'O apagão no meio do jogo.',
  'Uma selfie no velório.',
  'O preço do aluguel.',
  'Um gato que derruba tudo.',
  'A impressora sem tinta.',
  'Um político arrependido.',
  'O Wi-Fi da casa da avó.',
  'Uma dança vergonhosa no TikTok.',
  'O horário de verão.',
  'Um mocotó com limão.',
  'A festa surpresa que deu errado.',
  'Um espeto de gato na churrasqueira.',
  'O despertador às 5 da manhã.',
  'Uma marmita vazando na mochila.',
  'O erro 404 da vida.',
  'Um funkeiro aposentado.',
  'A fatura do cartão de crédito.',
  'Um clipe de k-pop.',
  'O pisca-alerta da mudança.',
  'Uma barata voadora.',
  'O Wi-Fi caindo na reunião.',
  'Um tio bêbado no churrasco.',
  'A farofa pronta.',
  'Um pão na chapa com requeijão.',
  'O GPS que te leva pro lugar errado.',
  'Uma dívida eterna.',
  'O juiz do VAR.',
  'Um cachorro caramelo.',
  'A quarentena sem fim.',
  'Um BBB de 24 horas.',
  'O salário no quinto dia útil.',
  'Uma fofoca de elevador.',
  'O dedo mindinho na quina da cama.',
  'Um samba de raiz.',
  'A feira de domingo.',
  'Um passinho errado.',
  'O trânsito da marginal.',
  'Uma promoção que era mentira.',
  'O gol da virada.',
  'Um cocô de pombo na cabeça.',
  'A voz do GPS.',
  'Um churros de feira.',
  'O horário de pico.',
];
