import { AskCardData } from '../asks';

export const ASKS_PT_BR: AskCardData[] = [
  { text: 'Qual é o prazer secreto do Batman?', pick: 1 },
  { text: 'O que acabou com meu último relacionamento?', pick: 1 },
  { text: 'Qual é o próximo brinde do McLanche Feliz?', pick: 1 },
  { text: 'Qual é meu talento secreto?', pick: 1 },
  { text: 'O que me dá gases incontroláveis?', pick: 1 },
  { text: 'Qual é a forma mais emo de expressar meus sentimentos?', pick: 1 },
  { text: 'O que deixaria a vovó perturbada, mas estranhamente encantada?', pick: 1 },
  { text: 'O que nunca falha em animar a festa?', pick: 1 },
  { text: 'Qual é o presente que continua dando?', pick: 1 },
  { text: 'O que eu trouxe de volta do México?', pick: 1 },
  { text: 'Do que tem uma tonelada no céu?', pick: 1 },
  { text: 'O que ajuda o presidente a relaxar?', pick: 1 },
  { text: 'O que eu trarei de volta no tempo para convencer as pessoas de que sou um mago poderoso?', pick: 1 },
  { text: 'Qual é a forma mais horrível de morrer?', pick: 1 },
  { text: 'Qual é a coisa mais polêmica no meu currículo?', pick: 1 },
  { text: 'Qual é o melhor amigo de uma garota?', pick: 1 },
  { text: 'O que meus pais estão escondendo de mim?', pick: 2 },
  { text: 'Qual é o superpoder mais inútil?', pick: 1 },
  { text: 'Qual é meu espírito animal?', pick: 1 },
  { text: 'Qual é a pior coisa a dizer numa entrevista de emprego?', pick: 1 },
  { text: 'O que eu disse para o policial?', pick: 1 },
  { text: 'Por que eu não consigo dormir à noite?', pick: 1 },
  { text: 'O que há de novo no meu pesadelo?', pick: 1 },
  { text: 'O que a vizinhança está fofocando?', pick: 2 },
  { text: 'Qual é o segredo do meu sucesso?', pick: 1 },
  { text: 'O que a vovó encontrou na gaveta?', pick: 1 },
  { text: 'Qual é o verdadeiro motivo do apagão?', pick: 1 },
  { text: 'O que tem dentro da minha marmita?', pick: 1 },
  { text: 'O que o carteiro viu pela janela?', pick: 1 },
  { text: 'Qual é a desculpa para chegar atrasado?', pick: 1 },
  { text: 'O que a Ana Maria Braga vai cozinhar hoje?', pick: 1 },
  { text: 'Qual é o prato do jantar de Natal?', pick: 1 },
  { text: 'O que o instrutor de autoescola nunca esquece?', pick: 1 },
  { text: 'Qual é o conteúdo do meu histórico de buscas?', pick: 1 },
  { text: 'O que o médico realmente encontrou no meu exame?', pick: 2 },
  { text: 'Qual é a senha do meu Wi-Fi?', pick: 1 },
  { text: 'O que o gato fez de madrugada?', pick: 1 },
  { text: 'Qual é o melhor presente de Dia dos Namorados?', pick: 1 },
  { text: 'O que o chefe descobriu sobre mim?', pick: 1 },
  { text: 'O que estragou o churrasco?', pick: 1 },
  { text: 'Qual é a manchete do jornal amanhã?', pick: 1 },
  { text: 'O que tem atrás do sofá?', pick: 1 },
  { text: 'Qual é a real utilidade do umbigo?', pick: 1 },
  { text: 'O que eu postei sem querer?', pick: 1 },
  { text: 'Qual é a desculpa do goleiro?', pick: 1 },
  { text: 'O que o padre disse no confessionário?', pick: 1 },
  { text: 'Qual é o ritual para o time ganhar?', pick: 1 },
  { text: 'O que a cartomante previu?', pick: 1 },
  { text: 'Qual é a última coisa que o boi viu?', pick: 3 },
  { text: 'O que tem no fundo da piscina?', pick: 1 },
  { text: 'Qual é o segredo da receita da vó?', pick: 1 },
  { text: 'O que o motorista de aplicativo escutou?', pick: 1 },
  { text: 'Qual é o motivo da briga de família?', pick: 1 },
  { text: 'O que a ex postou hoje?', pick: 1 },
  { text: 'Qual é o novo sabor de pizza?', pick: 1 },
  { text: 'O que tem dentro da caixa de sapato?', pick: 1 },
  { text: 'Qual é o conselho do pai?', pick: 1 },
  { text: 'O que o personal trainer falou?', pick: 1 },
  { text: 'Qual é o problema da humanidade?', pick: 1 },
  { text: 'O que me deixa bonito de verdade?', pick: 1 },
  { text: 'Qual é a arma secreta da seleção?', pick: 1 },
  { text: 'O que o juiz não pode descobrir?', pick: 1 },
  { text: 'Qual é o sinal de que o mundo está acabando?', pick: 2 },
  { text: 'O que o taxista filosofou?', pick: 1 },
  { text: 'Qual é o gosto da vingança?', pick: 1 },
  { text: 'O que tem no meu travesseiro?', pick: 1 },
  { text: 'Qual é o verdadeiro significado da vida?', pick: 1 },
  { text: 'O que a tia postou no grupo?', pick: 1 },
  { text: 'Qual é a melhor forma de pedir demissão?', pick: 1 },
  { text: 'O que o vizinho ouviu à noite?', pick: 1 },
  { text: 'Qual é o segredo para emagrecer?', pick: 2 },
  { text: 'O que o pastor prometeu?', pick: 1 },
  { text: 'Qual é a desculpa do político?', pick: 1 },
  { text: 'O que tem no meu congelador?', pick: 1 },
  { text: 'Qual é o efeito colateral do remédio?', pick: 1 },
  { text: 'O que o cientista criou em segredo?', pick: 1 },
  { text: 'Qual é a senha do cofre?', pick: 1 },
  { text: 'O que o gênio da lâmpada escondeu?', pick: 1 },
  { text: 'Qual é a minha vocação?', pick: 1 },
  { text: 'O que me trouxe até aqui?', pick: 1 },
  { text: 'Qual é o plano infalível para ficar rico?', pick: 1 },
  { text: 'O que o alienígena quer?', pick: 1 },
  { text: 'Qual é a prova de que o universo me odeia?', pick: 1 },
  { text: 'O que a professora descobriu na prova?', pick: 1 },
  { text: 'Qual é o melhor jeito de conquistar a sogra?', pick: 1 },
  { text: 'O que o instrutor do Detran reprovou?', pick: 1 },
  { text: 'Qual é o recheio do pastel?', pick: 1 },
  { text: 'O que a vidente viu na borra de café?', pick: 1 },
  { text: 'Qual é a minha desculpa para faltar amanhã?', pick: 1 },
  { text: 'O que o porteiro presenciou?', pick: 1 },
  { text: 'Qual é a vantagem de ser adulto?', pick: 1 },
  { text: 'O que o bicheiro apostou?', pick: 1 },
  { text: 'Qual é o meu legado para a humanidade?', pick: 1 },
  { text: 'O que a Alexa ouviu?', pick: 1 },
  { text: 'Qual é a verdadeira história do Brasil?', pick: 1 },
  { text: 'O que a sogra trouxe de presente?', pick: 1 },
  { text: 'Qual é a minha maior conquista?', pick: 1 },
  { text: 'O que me faz acordar de manhã?', pick: 1 },
  { text: 'Qual é o destino do dinheiro do imposto?', pick: 3 },
  { text: 'O que o influencer patrocinou?', pick: 1 },
  { text: 'Qual é a melhor desculpa para terminar?', pick: 1 },
  { text: 'O que tem dentro do colchão?', pick: 1 },
  { text: 'Qual é a regra da casa?', pick: 1 },
  { text: 'O que o amigo secreto vai me dar?', pick: 1 },
  { text: 'Qual é a minha herança?', pick: 1 },
];
